### ISSUE TITLE
Setting org-html-htmlize-output-type in the Org file

### ISSUE THREAD

**Issue by larstvei** [jessekelly881/Theme-Rethink#1]
You can use [file variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables) for this!

Add this to the top of your org file:

```
# -*- org-html-htmlize-output-type: css -*-
```

Or add this to the bottom of your org file:

```
* COMMENT Local Variables
  # Local Variables:
  # org-html-htmlize-output-type: css
  # End:
```

I often prefer to use the latter, because it's more flexible. A neat use case for this is to export to HTML on save.

```
* COMMENT Local Variables
  # Local Variables:
  # org-html-htmlize-output-type: css
  # eval: (add-hook 'after-save-hook 'org-html-export-to-html nil t)
  # End:
```

You have to reopen the file for it to take effect, and emacs will query you whether you would like to apply the changes (you can say never ask again). If reopening the file is too much hassle, going `M-x normal-mode` will also work 👍

**Comment by jessekelly881** [comment]
Amazing! Thank you so much! Change made to readme. Also, I totally plan on using this in the future. Super useful.
