### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by larstvei** [jessekelly881/Theme-Rethink#2]
Hi!

I would like to use your theme and make some changes to it, preferably forking the repository.

Is this okay with you?

If you want anyone to be able to fork your project, you should add a [license](https://choosealicense.com/) to the project 🙂

**Comment by jessekelly881** [comment]
Hi! You can absolutely fork it. If it's not too much to ask I would
appreciate some credit for it though. I am traveling at the moment but when
I get the chance I will add a license to the project. Also, I always
appreciate a merge request if you add anything useful! Enjoy!

**Comment by larstvei** [comment]
Thank you!

It's of course not too much to ask. I'll provide a link to your repository in the README. If you add a license and copyright, I'll try to update the fork to include it.
